name: Cloud-gov Local Build

on: push

jobs:
  echo:
    name: Simple Echo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Workflow started"

  build:
    runs-on: ubuntu-latest
    needs: echo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build R image on CloudFoundry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
