name: Cloud-gov Local Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build R image on CloudFoundry
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: user/app:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
