name: Cloud-gov Local Build

on: push

jobs:
  echo:
    name: Simple Echo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Echo
        run: echo "Workflow started"

  build:
    runs-on: ubuntu-latest
    needs: echo

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          tag_with_ref: true
