name: Cloud-gov Local Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Make build.sh executable
        run: chmod +x .github/build.sh

      - name: Set up cloud foundry CLI
        run: sudo .github/build.sh
        shell: bash

      - name: Make install_cflocal.sh executable
        run: chmod +x .github/install_cflocal.sh

      - name: Install cfLocal
        run: .github/install_cflocal.sh
        shell: bash

      - name: Check that the plugin is recognized
        run: cf plugins

      - name: Stage R Shiny app
        run: cf local stage nars-dataextr -b https://github.com/cloudfoundry/r-buildpack

      - name: list files
        run: ls -r .

      - name: Push Docker image
        id: docker_push
        run: docker push docker.pkg.github.com/testorg-2020/test_eforms_nars/nars-dataextr:${{ github.run_id }}
