name: Cloud-gov Local Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up coud foundry CLI and cflocal
        run: |
          # make file runnable, might not be necessary
          chmod +x "${GITHUB_WORKSPACE}/.github/build.sh"
          # run script
          "${GITHUB_WORKSPACE}/.github/build.sh"

  stage:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Stage R Shiny app
        run: cf local stage -b https://github.com/cloudfoundry/r-buildpack
