name: Testing Python Scripts

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Get App Name from local.yml
        shell: python
        run: |
          import os
          f = open(os.environ["GITHUB_WORKSPACE"] + "/local.yml", "r")
          for line in f.readlines():
            if line.startswith("- name:"):
              os.environ["DOCKER_TAGNAME"] = line.split(":")[1].strip())
        env:
          docker_tagname: ""

      # - name: Print new environment variable
      #   run: echo ${{ docker_tagname }}
