name: Testing Python or Bash Scripts to update env

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ""
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get App Name from local.yml
        shell: python
        run: |
          import os
          os.chdir(os.environ["GITHUB_WORKSPACE"])
          f = open("local.yml", "r")
          for line in f.readlines():
            if line.startswith("- name:"):
              print(line.split(":")[1].strip())
              os.putenv("APP_NAME", line.split(":")[1].strip())
              # os.environ["APP_NAME"] = line.split(":")[1].strip()
          f.close()

      - name: Print new environment variable
        run: echo $APP_NAME

      - name: Bash script to update
        shell: bash
        run: |
          cat local.yml | while read -r line;
          do if [[ $line = *name:* ]]; then
          echo app_name=echo "$line" | cut -d ":" -f 2 | xargs;
          fi;
          done >> $GITHUB_ENV

      - name: Print new environment variable
        run: echo ${{ env.app_name }}
