name: Testing Python Scripts

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      APP_NAME: ""
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Get App Name from local.yml
        shell: python
        run: |
          import os
          os.chdir(os.environ["GITHUB_WORKSPACE"])
          f = open("local.yml", "r")
          for line in f.readlines():
            if line.startswith("- name:"):
              print(line.split(":")[1].strip())
              os.putenv("APP_NAME", line.split(":")[1].strip())
              # os.environ["APP_NAME"] = line.split(":")[1].strip()
          f.close()

      - name: Print new environment variable
        run: echo $APP_NAME
